version: "3.3"

services: 
  web: 
    build: . 
    command: python manage.py runserver  
    volumes:
      - .:/code 
    ports:
      - 8000:8000 
    depends_on:
      - db 

  db: 
    image: postgres:13
    restart: always 
    environment: 
      - SECRET_KEY=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_SERVICE=postgres
      - DB_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data: {}